DROP TABLE IF EXISTS songs;

CREATE TABLE SONGS(
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    TITLE VARCHAR(250) NOT NULL,
    ARTIST VARCHAR(250) NOT NULL,
    ALBUM VARCHAR(250) NOT NULL
);

-- INSERT INTO DD_SONGS(ID, TITLE, ARTIST, ALBUM) VALUES (1, 'Toss A Coin To Your Witcher', 'Joey Batey', 'The Witcher OST');