DROP TABLE IF EXISTS DD_SONGS;

CREATE TABLE DD_SONGS
(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    TITLE       VARCHAR(250) NOT NULL,
    ARTIST      VARCHAR(250) NOT NULL,
    ALBUM       VARCHAR(250) NOT NULL,
    CREATE_DATE TIMESTAMP    NOT NULL,
    MODIFY_DATE TIMESTAMP    NOT NULL
);

-- INSERT INTO DD_SONGS(ID, TITLE, ARTIST, ALBUM) VALUES (1, 'Toss A Coin To Your Witcher', 'Joey Batey', 'The Witcher OST');